image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

buildGatsby:
  stage: build
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  # specify the artifacts to save
  artifacts:
    paths:
      - public
  only:
    - master
      
deployGatsby:
  stage: deploy
  only:
  - master
  dependencies:
  - buildGatsby
  script:
    - apt-get update -qq && apt-get install -y -qq rsync
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    # set ssh private key
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # set known hosts
    - echo "$SSH_KNOWN_HOSTS"
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -avzh --delete public/* $SSH_USERNAME@$SSH_HOST:/home/consgm5k/webapps/conspac/